

var myMenu =
		[
			_cmSplit,
			//[null,'我的桌面','mainMenu.html',null,'我的桌面'],
			[null,'','',null,''],
			_cmSplit,
			[null,'客户关系',null,null,'客户关系',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户信息','customers.html',null,'客户信息'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','联系人','linkMans.html',null,'联系人'],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户意见','feedbackInfos.html',null,'客户意见'],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','行业分类','industrys.html',null,'行业分类'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户类别','categorys.html',null,'客户类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户性质','customerTypes.html',null,'客户性质'],
				],														
			],
			
			[null,'广告资源',null,null,'广告资源',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','资源管理','resources.html',null,'资源管理'],	
			    ['<img src="menu/includes/js/ThemeOffice/menus.png" />','投放组合','compages.html',null,'投放组合'],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','价格类别','priceTypes.html',null,'价格类别'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','指定信息','specifics.html',null,'指定信息'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','载体分类','carrierTypes.html',null,'载体分类'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','媒体机构','resourceTypes.html',null,'媒体机构'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','频道栏目','resourceChannels.html',null,'频道栏目'],
				],				
																
			],
			
			[null,'广告素材',null,null,'广告素材',
//				['<img src="menu/includes/js/ThemeOffice/menus.png" />','产品品牌','brands.html',null,'产品品牌'],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','产品分类','productCategorys.html',null,'产品分类'],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','广告素材','matters.html',null,'广告素材'],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','发布备注','publishMemos.html',null,'发布备注'],
				// ['<img src="menu/includes/js/ThemeOffice/menus.png" />','发布信息','publishedInfos.html',null,'发布信息'],												
			],
			
			_cmSplit,
			[null,'订单管理',null,null,'订单管理',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','合同信息',null,null,'合同信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','代理合同','contracts.html?type=1',null,'代理合同'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','直接合同','contracts.html?type=2',null,'直接合同'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','其他合同','contracts.html?type=3',null,'其他合同'],
				],
//				_cmSplit,
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','销售订单','orders.html',null,'销售订单'],
				_cmSplit,
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','资源查询','queryAdres.html',null,'资源查询'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','订单日志','orderLogs.html',null,'订单日志'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','播出证明','broReport.html',null,'播出证明'],		
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','订单类别','orderCategorys.html',null,'订单类别'],
				],	
				
			],
			_cmSplit,
			
			[null,'结算管理',null,null,'结算管理',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','到款入录','incomes.html',null,'到款入录'],
				//_cmSplit,
				//['<img src="menu/includes/js/ThemeOffice/menus.png" />','到款分配','incomePulls.html',null,'到款分配'],
				//['<img src="menu/includes/js/ThemeOffice/menus.png" />','取消分配','incomePulls.html',null,'取消分配'],
				_cmSplit,
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','到款统计','incomes.html',null,'到款统计'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','到款分配','incomePulls.html',null,'到款分配'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','欠款统计','incomes.html',null,'欠款统计'],
				_cmSplit,
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','到款方式','incomeModes.html',null,'到款方式'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','收款用途','incomePurposes.html',null,'收款用途'],
				],	
			],
			_cmSplit,
			
			[null,'发布管理',null,null,'发布管理',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','广告编排1','publishedInfos.html',null,'广告编排1'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','广告编排2','publishInfos.html',null,'广告编排2'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','垫片广告','appendTree.html',null,'垫片广告'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','垫片查询','a.html',null,'垫片查询'],
			],
			_cmSplit,	
					
			[null,'综合管理',null,null,'综合管理',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','信息管理',null,null,'信息管理',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','最新通知','oaInfos.html',null,'最新通知'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','最新信息','oaInfos.html',null,'最新信息']
				],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','考勤管理','',null,'考勤管理',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','请假','oaApplyInfos.html',null,'请假'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','加班','oaApplyInfos.html',null,'加班']
				],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','办公用品',null,null,'办公用品',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','采购登记','oaProductInfos.html',null,'采购'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','领用登记','oaProductUseds.html',null,'领用'],
				],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','资产管理',null,null,'资产管理',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','资产登记','editOaAssets.html',null,'资产登记'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','资产浏览','oaAssetss.html',null,'资产浏览'],
				],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','话费管理',null,null,'话费管理',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','部门话费','oaTeleExpensess.html',null,'部门话费'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','话费登记','editOaTeleExpenses.html',null,'资产登记'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','话费统计','oaTeleExpensessQuery.html',null,'话费统计'],
				],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','信息类别','oaInfoTypes.html',null,'信息类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','事件类别','categorys.html',null,'事件类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户性质','customerTypes.html',null,'客户性质'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','耗材类别','oaProductTypes.html',null,'耗材类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','资产类别','oaAssetsTypes.html',null,'资产类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','资产状态','oaAssetsStates.html',null,'资产状态'],		
				],				

			],
			_cmSplit,
			
			[null,'文档管理',null,null,'文档管理',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','目录管理','oaDocumentCatalogs.html',null,'目录管理'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','文档浏览','oaDocuments.html',null,'文档浏览'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','发布文档','oaDocuments.html',null,'发布文档'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','目录权限类别','oaDocumentCatalogPermitTypes.html',null,'目录权限类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','文件','oaDocumentFiles.html',null,'文件'],	
				],
			],
			_cmSplit,
			
			[null,'日常工具',null,null,'日常工具',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','日程安排','oaCalendarEvents.html',null,'日程安排'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','名片管理','oaBusinessCards.html',null,'名片管理'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','邮编区号','oaAreaPcs.html',null,'邮编区号'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','我的便笺','oaScratchpads.html',null,'我的便笺'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','城市信息','oaAreaCitys.html',null,'城市信息'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','计算器','calculator.html',null,'计算器'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','名片类别','oaBusinessCardTypes.html',null,'名片类别'],
				]
			],
			
			_cmSplit,
			
			[null,'统计分析',null,null,'统计分析',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户统计',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','区间统计','customerAnalyze.html',null,'区间统计'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','全年统计','yearAnalyze.html',null,'全年统计'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','业务员统计','businessAnalyze.html',null,'业务员统计'],
				],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','载体统计',null,null,'载体统计',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','区间统计','carrierScopeAnalyze.html',null,'区间统计'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','全年统计','carrierAllYearAnalyze.html',null,'全年统计'],					
				],	
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','品牌统计',null,null,'品牌统计',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','客户品牌投放量','customerProductRelIncome.html',null,'客户品牌投放量'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','行业品牌投放量','industryProductRelIncome.html',null,'行业品牌投放量'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','广告类型品牌投放量','advTypeProductRelIncome.html',null,'广告类型品牌投放量'],
				],
			],
			_cmSplit,
			 
			[null,'工作流程',null,null,'工作流程',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','流程管理','oaWorkFlows.html',null,'流程管理'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','办公申请','oaApplyInfos.html',null,'办公申请'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','办公审批','oaWorkFlowChecks.html',null,'流程审批'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','流程类别','oaWorkFlowTypes.html',null,'流程类别'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','审批结果','oaWorkFlowCheckResults.html',null,'审批结果'],
				],
			],
			_cmSplit,			
			
			[null,'系统管理',null,null,'系统管理',
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','组织信息','orgs.html',null,'组织信息'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','部门信息','branchs.html',null,'部门信息'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','职位信息','roles.html',null,'职位信息'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','用户信息','users.html',null,'用户信息'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','权限控制','sysPermitManager.html',null,'权限控制'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','在线用户','activeUsers.html',null,'在线用户'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','重载选项','reload.html',null,'重载选项'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','刷新缓存','flush.html',null,'刷新缓存'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','访问记录','clickstreams.html',null,'访问记录'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','报表工具','reports/index.jsp',null,'报表工具'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','系统事件','sysEvents.html',null,'系统事件'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','系统参数','sysParams.html',null,'系统参数'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','系统采单','sysMenus.html',null,'系统菜单'],
				['<img src="menu/includes/js/ThemeOffice/menus.png" />','基本信息',null,null,'基本信息',
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','事件状态','sysEventStates.html',null,'事件状态'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','事件类型','sysEventTypes.html',null,'事件类型'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','系统提示方式','sysPromptModes.html',null,'系统提示方式'],
					['<img src="menu/includes/js/ThemeOffice/menus.png" />','用户类别','sysUserTypes.html',null,'用户类别'],	
				],
							
				
			],
			_cmSplit,

			//[null,'高级搜索','common/search.html',null,'高级搜索'],
			//[null,'退出登录','logout.jsp',null,'退出登录']
			
		];
		cmDraw ('myMenuID', myMenu, 'hbr', cmThemeOffice, 'ThemeOffice');
		 