var myMenu =
		[
			[null,'我的桌面','../main/destop.htm',null,'我的桌面'],
			_cmSplit,
			[null,'数据分类',null,null,'分类数据',
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','广告资源',null,null,'资源管理',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index3.htm',"_blank",'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','客户资源',null,null,'客户资源',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','订单管理',null,null,'订单管理',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],	
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','结算管理',null,null,'结算管理',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','编播管理',null,null,'编播管理',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],	
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','地址信息',null,null,'地址信息',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],					
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','人力资源',null,null,'人力资源',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],
				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它',null,null,'其它',
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,'主菜单'],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
					['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
				],																		
				
			],
			
			_cmSplit,
			[null,'组织机构',null,null,'机构组织',
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','菜单管理','index2.php?option=com_menumanager',null,'菜单管理2'],
				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','主菜单','index2.php?option=com_menus&menutype=mainmenu',null,''],
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','其它菜单','index2.php?option=com_menus&menutype=othermenu',null,''],
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','顶部菜单','index2.php?option=com_menus&menutype=topmenu',null,''],
				['<img src="../menu/includes/js/ThemeOffice/menus.png" />','用户菜单','index2.php?option=com_menus&menutype=usermenu',null,''],
			],
			_cmSplit,
			[null,'系统权限',null,null,'权限',
				['<img src="../menu/includes/js/ThemeOffice/edit.png" />','单元内容',null,null,'内容管理',
					['<img src="../menu/includes/js/ThemeOffice/document.png" />','新闻', null, null,'新闻',
						['<img src="../menu/includes/js/ThemeOffice/edit.png" />', '新闻 条目', 'index2.php?option=com_content&sectionid=1',null,null],
						['<img src="../menu/includes/js/ThemeOffice/add_section.png" />', '新增/编辑 新闻 分类', 'index2.php?option=com_categories&section=1',null, null],
					],
					['<img src="../menu/includes/js/ThemeOffice/document.png" />','FAQs', null, null,'FAQs',
						['<img src="../menu/includes/js/ThemeOffice/edit.png" />', 'FAQs 条目', 'index2.php?option=com_content&sectionid=3',null,null],
						['<img src="../menu/includes/js/ThemeOffice/add_section.png" />', '新增/编辑 FAQs 分类', 'index2.php?option=com_categories&section=3',null, null],
					],
					['<img src="../menu/includes/js/ThemeOffice/document.png" />','新闻快讯', null, null,'新闻快讯',
						['<img src="../menu/includes/js/ThemeOffice/edit.png" />', '新闻快讯 条目', 'index2.php?option=com_content&sectionid=2',null,null],
						['<img src="../menu/includes/js/ThemeOffice/add_section.png" />', '新增/编辑 新闻快讯 分类', 'index2.php?option=com_categories&section=2',null, null],
					],
				],
				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/edit.png" />','所有内容条目','index2.php?option=com_content&sectionid=0',null,'管理内容条目'],
  				['<img src="../menu/includes/js/ThemeOffice/edit.png" />','静态内容管理','index2.php?option=com_typedcontent',null,'管理静态内容条目'],
  				_cmSplit,
  				['<img src="../menu/includes/js/ThemeOffice/add_section.png" />','单元管理','index2.php?option=com_sections&scope=content',null,'管理内容单元'],
				['<img src="../menu/includes/js/ThemeOffice/add_section.png" />','分类管理','index2.php?option=com_categories&section=content',null,'管理内容分类'],
				_cmSplit,
  				['<img src="../menu/includes/js/ThemeOffice/home.png" />','首页管理','index2.php?option=com_frontpage',null,'管理首页条目'],
  				['<img src="../menu/includes/js/ThemeOffice/edit.png" />','存档管理','index2.php?option=com_content&task=showarchive&sectionid=0',null,'管理存档条目'],
			],
			_cmSplit,
			[null,'系统参数',null,null,'系统参数',
				['<img src="../menu/includes/js/ThemeOffice/install.png" />','安装/卸载','index2.php?option=com_installer&element=component',null,'安装/卸载组件'],
  				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/component.png" />','联系人',null,null,'编辑联系人资料',
					['<img src="../menu/includes/js/ThemeOffice/component.png" />','管理联系人','index2.php?option=com_contact',null,'编辑联系人资料'],
					['<img src="../menu/includes/js/ThemeOffice/categories.png" />','联系人分类','index2.php?option=categories&section=com_contact_details',null,'管理联系人分类']
				],
				['<img src="../menu/includes/js/ThemeOffice/component.png" />','新闻联合','index2.php?option=com_syndicate',null,'管理网站新闻联合'
				],
				['<img src="../menu/includes/js/ThemeOffice/component.png" />','新闻导入',null,null,'新闻导入管理',
					['<img src="../menu/includes/js/ThemeOffice/edit.png" />','管理新闻导入','index2.php?option=com_newsfeeds',null,'管理新闻导入'],
					['<img src="../menu/includes/js/ThemeOffice/categories.png" />','管理新闻导入分类','index2.php?option=com_categories&section=com_newsfeeds',null,'管理新闻导入分类']
				],
				['<img src="../menu/includes/js/ThemeOffice/mass_email.png" />','群发邮件','index2.php?option=com_massmail&hidemainmenu=1',null,'群发邮件'
				],
				['<img src="../menu/includes/js/ThemeOffice/component.png" />','网站链接',null,null,'管理网站链接',
					['<img src="../menu/includes/js/ThemeOffice/edit.png" />','网站链接条目','index2.php?option=com_weblinks',null,'查看已有链接'],
					['<img src="../menu/includes/js/ThemeOffice/categories.png" />','网站链接分类','index2.php?option=categories&section=com_weblinks',null,'管理网站链接分类']
				],
				['<img src="../menu/includes/js/ThemeOffice/component.png" />','在线调查','index2.php?option=com_poll',null,'管理在线调查'
				],
				['<img src="../menu/includes/js/ThemeOffice/component.png" />','横幅广告',null,null,'横幅广告管理',
					['<img src="../menu/includes/js/ThemeOffice/edit.png" />','管理横幅广告','index2.php?option=com_banners',null,'活路的横幅广告'],
					['<img src="../menu/includes/js/ThemeOffice/categories.png" />','管理广告客户','index2.php?option=com_banners&task=listclients',null,'管理广告客户']
				],
			],
			_cmSplit,
			[null,'用户自定义',null,null,'用户自定义',
				['<img src="../menu/includes/js/ThemeOffice/install.png" />', '安装/卸载', 'index2.php?option=com_installer&element=module', null, '安装定制模块'],
				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/module.png" />', '网站模块', "index2.php?option=com_modules", null, '管理网站模块'],
				['<img src="../menu/includes/js/ThemeOffice/module.png" />', '后台模块', "index2.php?option=com_modules&client=admin", null, '管理后台模块'],
			],
			_cmSplit,
			[null,'广告资源',null,null,'资源管理',
				['<img src="../menu/includes/js/ThemeOffice/install.png" />', '安装/卸载', 'index2.php?option=com_installer&element=mambot', null, '安装定制触发器'],
				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/module.png" />', '网站触发器', "index2.php?option=com_mambots", null, '管理网站触发器'],
			],
			_cmSplit,
			[null,'安装',null,null,'安装列表',
				['<img src="../menu/includes/js/ThemeOffice/install.png" />','模版 - 网站','index2.php?option=com_installer&element=template&client=',null,'安装网站模版'],
				['<img src="../menu/includes/js/ThemeOffice/install.png" />','模版 - 后台','index2.php?option=com_installer&element=template&client=admin',null,'安装后台模版'],
				['<img src="../menu/includes/js/ThemeOffice/install.png" />','语言','index2.php?option=com_installer&element=language',null,'安装语言'],
				_cmSplit,
				['<img src="../menu/includes/js/ThemeOffice/install.png" />', '组件','index2.php?option=com_installer&element=component',null,'安装/卸载组件'],
				['<img src="../menu/includes/js/ThemeOffice/install.png" />', '模块', 'index2.php?option=com_installer&element=module', null, '安装/卸载模块'],
				['<img src="../menu/includes/js/ThemeOffice/install.png" />', '触发器', 'index2.php?option=com_installer&element=mambot', null, '安装/卸载触发器'],
			],
			_cmSplit,
			[null,'短信',null,null,'消息管理',
				['<img src="../menu/includes/js/ThemeOffice/messaging_inbox.png" />','收件箱','index2.php?option=com_messages',null,'站内短信'],
				['<img src="../menu/includes/js/ThemeOffice/messaging_config.png" />','配置','index2.php?option=com_messages&task=config&hidemainmenu=1',null,'配置']
  			],
			_cmSplit,
			[null,'系统',null,null,'系统管理',
				['<img src="../menu/includes/js/ThemeOffice/checkin.png" />', '全部放回', 'index2.php?option=com_checkin', null,'放回所有取出的条目'],
			],
			_cmSplit,
			[null,'帮助','index2.php?option=com_admin&task=help',null,null]
		];
		cmDraw ('myMenuID', myMenu, 'hbr', cmThemeOffice, 'ThemeOffice'); 